name: epub_shelf
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: any
  permission: any
  shared_preferences: any
  sqflite: any

  epub_package:
    path: ../epub-package

flutter:
  uses-material-design: true
  assets:
    - assets/
